// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/LiftDownWhilePressed.h"
#include "Commands/LiftUpWhilePressed.h"
#include "Commands/TankDrive.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    mainController.reset(new frc::Joystick(0));
    
    liftDown.reset(new frc::JoystickButton(mainController.get(), 1));
    liftDown->WhileHeld(new LiftDownWhilePressed());
    liftUp.reset(new frc::JoystickButton(mainController.get(), 4));
    liftUp->WhileHeld(new LiftUpWhilePressed());

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("TankDrive", new TankDrive());
    frc::SmartDashboard::PutData("Lift Down While Pressed", new LiftDownWhilePressed());
    frc::SmartDashboard::PutData("Lift Up While Pressed", new LiftUpWhilePressed());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getMainController() {
   return mainController;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
